### PR TITLE
Add `Jenkinsfile`

### PR DESCRIPTION
**Pull request by basil**

### CODE REVIEW

**Comment by basil** [comment]
@timja This repository looks so dusty that there isn't even a job for it on https://ci.jenkins.io/ - what's the most appropriate way for me to request one? Do I need to file an INFRA ticket?

**Comment by MarkEWaite** [comment]
> @timja This repository looks so dusty that there isn't even a job for it on https://ci.jenkins.io/ - what's the most appropriate way for me to request one? Do I need to file an INFRA ticket?

Since ci.jenkins.io is currently not under full configuration as code, I've added the repository to https://ci.jenkins.io/job/jenkinsci-libraries/ .  A job should appear on ci.jenkins.io in that folder once the repo has a Jenkinsfile

**Comment by timja** [comment]
> > @timja This repository looks so dusty that there isn't even a job for it on [ci.jenkins.io](https://ci.jenkins.io/) - what's the most appropriate way for me to request one? Do I need to file an INFRA ticket?
> 
> Since ci.jenkins.io is currently not under full configuration as code, I've added the repository to [ci.jenkins.io/job/jenkinsci-libraries](https://ci.jenkins.io/job/jenkinsci-libraries/) . A job should appear on ci.jenkins.io in that folder once the repo has a Jenkinsfile
> 
> See [ci.jenkins.io/job/jenkinsci-libraries/job/extras-memory-monitor](https://ci.jenkins.io/job/jenkinsci-libraries/job/extras-memory-monitor/)

noooo, the preferred approach is to rename the repo so it doesn't rely on anyones access.

`(lib-.*|.*-lib)`

`lib-` is the preferred pattern

**Comment by basil** [comment]
Thank you, Mark! I think modernizing this repository is risky enough without also having to deal with a renaming at the same time. Let's start with the former and we can always come back to the latter in the future.

**Comment by timja** [comment]
> Thank you, Mark! I think modernizing this repository is risky enough without also having to deal with a renaming at the same time. Let's start with the former and we can always come back to the latter in the future.

renaming repo is trivial and what we've done with every other one of these

**Pull request merged**
